config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    member do
      get :confirm_destroy
    end

    collection do
      get :published
    end
  end
  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :author, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout :layout_or_not
  before_action :authenticate, only: [:destroy, :confirm_destroy]

  def new
    @post = Post.new(author: session[:author])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      session[:author] = @post.author
      flash[:notice] = "Post dodany pomyślnie."
      redirect_to posts_path
    else
      render action: 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:notice] = "Post zaktualizowany pomyślnie."
      redirect_to posts_path
    else
      render action: 'edit'
    end
  end

  def index
    @posts = Post.all
  end

  def published
    @posts = Post.where(published: true)
    render action: "index"
  end

  def show
    @post = Post.find(params[:id])
  end

  def confirm_destroy
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Pomyślnie usunięto wpis"
    redirect_to posts_path
  end

  def post_params
    params.require(:post).permit(:title, :author, :body, :published)
  end

  def layout_or_not
    if params[:skip_layout] == "true"
      false
    else
      'application'
    end
  end

  def authenticate
    authenticate_or_request_with_http_basic "Podaj haslo" do |name, password|
      name == "username" && password == "secret"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def format_date(date)
    date.strftime("%d.%m.%Y")
  end

  def post_footer(post)
    "<cite>#{post.author}, #{format_date(post.created_at)}</cite>".html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class= "container">
    <div class= "page-header">
      <% if flash[:notice].present? %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <h1>Demonstracja CRUD</h1>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/jumbotron.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crud</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class= "container">
    <div class= "page-header">
      <div class="jumbotron">
        <h1>WOW!</h1>
      </div>
      <% if flash[:notice].present? %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.present? %>
  <div class="alert alert-danger">
    <p>Wystąpiły następujące błędy</p>
    <ol>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message.titleize %></li>
      <% end %>
    </ol>
  </div>
<% end %>
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title, "Tytuł" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :author, "Autor" %>
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body, "Treść" %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :published, "Opublikowany?" %>
    <%= f.check_box :published, class: "form-control" %>
  </div>
  <%= f.submit button_name, class: "btn btn-primary"%> <!-- klasa btn btn-primary koloruje przycisk na zielono -->
<% end %>

app/views/posts/confirm_destroy.html.erb
<h3><%= @post.title %></h3>
<%= simple_format @post.body %>

<p>Czy na pewno chcesz usunąć?</p>
<p>
  <%= link_to "Tak", post_path(@post), method: :delete, class: "btn btn-danger" %>
  <%= link_to "Nie", posts_path, class: "btn btn-default" %>
</p>

app/views/posts/edit.html.erb
<h3>Edycja posta</h3>
<%= render partial: "form", locals: { button_name: "Zaktualizuj wpis"} %>

app/views/posts/index.html.erb
<h3>Lista wpisów</h3>

<p><%= link_to "Dodaj nowy wpis", new_post_path, class: "btn btn-success" %></p>
<p>login: "username", hasło: "secret"

<ul class="nav nav-tabs">
  <li <% if params[:action] == "index" %>class="active"<% end %>><%= link_to "Wszystkie", posts_path %></li>
  <li <% if params[:action] == "published" %>class="active"<% end %>><%= link_to "Opublikowane", published_posts_path %></li>
</ul>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Tytuł</th>
      <th>Autor</th>
      <th>Opublikowany?</th>
      <th>Treść</th>
      <th>Akcje</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title %></td>
        <td><%= post.author %></td>
        <td><%= post.published ? "tak" : "nie" %></td>
        <td><%= simple_format post.body %></td>
        <td>
          <%= link_to "Pokaż", post_path(post), class: "btn btn-default btn-xs" %>
          <%= link_to "Edytuj", edit_post_path(post), class: "btn btn-primary btn-xs" %>
          <%= link_to "Usuń", confirm_destroy_post_path(post), class: "btn btn-danger btn-xs" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h3>Dodawanie nowego posta</h3>
<%= render partial: "form", locals: { button_name: "Dodaj nowy wpis"} %>

app/views/posts/show.html.erb
<h3><%= @post.title %></h3>

<%= simple_format @post.body %>

<p><%= post_footer(@post) %></p>

<p><%= link_to "Wróć do spisu", posts_path %></p>